repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        exclude: '\.lock.*'
      - id: debug-statements

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.26
    hooks:
      - id: pip-compile
        name: '[BUILD] Pip-compile'
        args: [requirements.txt, -o, requirements.txt]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.4
    hooks:
      - id: ruff
        name: '[BE] Ruff'
        args: ['--fix', '--unsafe-fixes', '--exit-non-zero-on-fix']

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        name: '[BE] Black formatter'

  - repo: https://github.com/pycqa/isort
    rev: 6.0.0
    hooks:
      - id: isort
        name: '[BE] Isort imports'

  # - repo: local
  #   hooks:
  #     - id: pytest
  #       name: '[BE] Pytest'
  #       stages: [commit]
  #       language: system
  #       entry: pytest --cov=src tests/
  #       types: [python]
  #       verbose: true
  #       pass_filenames: false
