"""feat: add auto buy/sell setting fields

Revision ID: 0aab12df96ac
Revises: 140444e02326
Create Date: 2025-02-27 11:18:36.900115

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0aab12df96ac"
down_revision: Union[str, None] = "140444e02326"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trading_settings",
        sa.Column("auto_buy_enabled", sa.Boolean(), default=False),
    )
    op.add_column(
        "trading_settings",
        sa.Column("auto_sell_enabled", sa.Boolean(), default=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trading_settings", "auto_sell_enabled")
    op.drop_column("trading_settings", "auto_buy_enabled")
    # ### end Alembic commands ###
