"""feat: add settings values to TradingSettings model

Revision ID: 140444e02326
Revises: 5e0bf98858f8
Create Date: 2025-02-26 15:33:38.361759

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "140444e02326"
down_revision: Union[str, None] = "5e0bf98858f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trading_settings_new",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(30), nullable=False, unique=True),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "take_profit_percentage",
            sa.Float(),
            nullable=False,
            server_default="0.05",
        ),
        sa.Column(
            "stop_loss_percentage",
            sa.Float(),
            nullable=False,
            server_default="0.05",
        ),
        sa.Column(
            "short_ema_time_period",
            sa.Integer(),
            nullable=False,
            server_default="5",
        ),
        sa.Column(
            "long_ema_time_period",
            sa.Integer(),
            nullable=False,
            server_default="20",
        ),
        sa.Column(
            "rsi_buy_threshold",
            sa.Integer(),
            nullable=False,
            server_default="30",
        ),
        sa.Column(
            "rsi_sell_threshold",
            sa.Integer(),
            nullable=False,
            server_default="70",
        ),
        sa.Column(
            "rsi_time_period",
            sa.Integer(),
            nullable=False,
            server_default="14",
        ),
        sa.Column(
            "buy_amount", sa.Float(), nullable=False, server_default="0.1"
        ),
        sa.Column(
            "buy_max_orders_threshold",
            sa.Integer(),
            nullable=False,
            server_default="2",
        ),
    )

    op.execute(
        """
        INSERT INTO trading_settings_new (id, name, created)
        SELECT id, name, created FROM trading_settings
    """
    )

    op.drop_table("trading_settings")

    op.rename_table("trading_settings_new", "trading_settings")

    op.create_index(
        "ix_trading_settings_id",  # Имя индекса
        "trading_settings",  # Имя таблицы
        ["id"],  # Колонки в индексе
        unique=False,  # Уникальность индекса
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trading_settings_old",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(30), nullable=False, unique=True),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
    )

    op.execute(
        """
        INSERT INTO trading_settings_old (id, name, created)
        SELECT id, name, created FROM trading_settings
    """
    )

    op.drop_table("trading_settings")

    op.rename_table("trading_settings_old", "trading_settings")
    # ### end Alembic commands ###
