"""feat: add cascade parametr to OrderBuy model

Revision ID: 41b8c9f404ca
Revises: a3973b6d72e8
Create Date: 2025-02-22 11:28:46.861625

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "41b8c9f404ca"
down_revision: Union[str, None] = "a3973b6d72e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
