"""feat: add OrderBuy and OrderSell models

Revision ID: a3973b6d72e8
Revises: d5f4faf217f6
Create Date: 2025-02-20 22:08:31.453354

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a3973b6d72e8"
down_revision: Union[str, None] = "d5f4faf217f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders_buy",
        sa.Column("from_token", sa.String(length=30), nullable=False),
        sa.Column("to_token", sa.String(length=30), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_orders_buy_id"), "orders_buy", ["id"], unique=False
    )
    op.create_table(
        "orders_sell",
        sa.Column("from_token", sa.String(length=30), nullable=False),
        sa.Column("to_token", sa.String(length=30), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("buy_order_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["buy_order_id"],
            ["orders_buy.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_orders_sell_id"), "orders_sell", ["id"], unique=False
    )
    op.drop_index("ix_orders_id", table_name="orders")
    op.drop_table("orders")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column(
            "created",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("from_token", sa.VARCHAR(length=30), nullable=False),
        sa.Column("price", sa.FLOAT(), nullable=False),
        sa.Column("action", sa.VARCHAR(length=4), nullable=False),
        sa.Column("to_token", sa.VARCHAR(length=30), nullable=False),
        sa.Column("amount", sa.FLOAT(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_orders_id", "orders", ["id"], unique=False)
    op.drop_index(op.f("ix_orders_sell_id"), table_name="orders_sell")
    op.drop_table("orders_sell")
    op.drop_index(op.f("ix_orders_buy_id"), table_name="orders_buy")
    op.drop_table("orders_buy")
    # ### end Alembic commands ###
