"""feat: add base app model and mapped types in the all models

Revision ID: baf5b4a8608a
Revises: 0ea0853fb8c0
Create Date: 2025-02-20 14:12:08.090243

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "baf5b4a8608a"
down_revision: Union[str, None] = "0ea0853fb8c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_table("orders")
        op.drop_table("prices_new")
    except Exception as e:
        print(e)

    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_id"), "orders", ["id"], unique=False)

    try:
        op.drop_column("prices", "created")
    except Exception as e:
        print(e)

    op.create_table(
        "prices_new",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "token_name",
            sa.String(length=30),
            nullable=False,
        ),
        sa.Column("price", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.execute(
        """
        INSERT INTO prices_new (id, token_name, price)
        SELECT id, token_name, price FROM prices
        """
    )

    op.drop_table("prices")

    op.rename_table("prices_new", "prices")

    op.create_index(op.f("ix_prices_id"), "prices", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prices_old",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("token_name", sa.String(length=30), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.execute(
        """
        INSERT INTO prices_old (id, created, token_name, price)
        SELECT id, created, token_name, price FROM prices
    """
    )

    op.drop_table("prices")

    op.rename_table("prices_old", "prices")
    op.drop_index(op.f("ix_orders_id"), table_name="orders")
    op.drop_table("orders")
    # ### end Alembic commands ###
