"""chore: add name field to TradingSettings model

Revision ID: bfb29f498a9a
Revises: d78f1f8bafaa
Create Date: 2025-02-23 16:08:02.456423

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.exc import OperationalError

# revision identifiers, used by Alembic.
revision: str = "bfb29f498a9a"
down_revision: Union[str, None] = "d78f1f8bafaa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.add_column(
            "trading_settings",
            sa.Column("name", sa.String(length=30), nullable=False),
        )
        op.create_unique_constraint(None, "trading_settings", ["name"])
    except (NotImplementedError, OperationalError):
        op.create_table(
            "new_trading_settings",
            sa.Column(
                "id",
                sa.Integer(),
                autoincrement=True,
                nullable=False,
            ),
            sa.Column(
                "created",
                sa.DateTime(timezone=True),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            ),
            sa.Column(
                "name",
                sa.String(255),
                unique=True,
                nullable=False,
            ),
            sa.PrimaryKeyConstraint("id"),
        )

        op.execute(
            """
            INSERT INTO new_trading_settings (id, created)
            SELECT id, created FROM trading_settings
        """
        )

        op.drop_table("trading_settings")

        op.rename_table("new_trading_settings", "trading_settings")
        op.create_index(
            op.f("ix_trading_settings_id"),
            "trading_settings",
            ["id"],
            unique=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_constraint(None, "trading_settings", type_="unique")
        op.drop_column("trading_settings", "name")
    except NotImplementedError:
        pass
    # ### end Alembic commands ###
