"""feat: add to_token and amount fields to Order

Revision ID: d5f4faf217f6
Revises: e70f9c7c540f
Create Date: 2025-02-20 19:11:48.475864

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5f4faf217f6"
down_revision: Union[str, None] = "e70f9c7c540f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders", sa.Column("to_token", sa.String(length=30), nullable=False)
    )
    op.add_column("orders", sa.Column("amount", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "amount")
    op.drop_column("orders", "to_token")
    # ### end Alembic commands ###
