"""feat: add Token, TradingPairSettings, TradingSettings models

Revision ID: d78f1f8bafaa
Revises: 41b8c9f404ca
Create Date: 2025-02-23 13:12:32.399275

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d78f1f8bafaa"
down_revision: Union[str, None] = "41b8c9f404ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tokens",
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("address", sa.String(length=128), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("address"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_tokens_id"), "tokens", ["id"], unique=False)
    op.create_table(
        "trading_settings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_trading_settings_id"),
        "trading_settings",
        ["id"],
        unique=False,
    )
    op.create_table(
        "trading_pair_settings",
        sa.Column("from_token_id", sa.Integer(), nullable=False),
        sa.Column("to_token_id", sa.Integer(), nullable=False),
        sa.Column("data_fetch_frequency", sa.Float(), nullable=False),
        sa.Column("trading_setting_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["from_token_id"],
            ["tokens.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_token_id"],
            ["tokens.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trading_setting_id"],
            ["trading_settings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_trading_pair_settings_id"),
        "trading_pair_settings",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_trading_pair_settings_id"), table_name="trading_pair_settings"
    )
    op.drop_table("trading_pair_settings")
    op.drop_index(
        op.f("ix_trading_settings_id"), table_name="trading_settings"
    )
    op.drop_table("trading_settings")
    op.drop_index(op.f("ix_tokens_id"), table_name="tokens")
    op.drop_table("tokens")
    # ### end Alembic commands ###
