"""feat: add fields to Order model

Revision ID: e70f9c7c540f
Revises: baf5b4a8608a
Create Date: 2025-02-20 18:55:28.368310

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e70f9c7c540f"
down_revision: Union[str, None] = "baf5b4a8608a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders", sa.Column("from_token", sa.String(length=30), nullable=False)
    )
    op.add_column("orders", sa.Column("price", sa.Float(), nullable=False))
    op.add_column(
        "orders", sa.Column("action", sa.String(length=4), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "action")
    op.drop_column("orders", "price")
    op.drop_column("orders", "from_token")
    # ### end Alembic commands ###
